export const depthReflectionLessons = [
  {
    number: "01",
    title: "Revision Lesson - This, That, These and Those",
    skill: "Grammar revision",
    model: "3P Model with Guided Discovery",
    pdfHref: "/docs/depth-reflection/lesson-1-demonstratives.pdf",
    preTeaching: [
      "This lesson was planned as a revision lesson to strengthen learners' understanding of the demonstratives this, that, these, and those. Although my Grade 6 learners had already met these words, some still found it difficult to choose the correct form when speaking or writing. They could identify singular and plural nouns, but often forgot to consider whether an object was near or far.",
      "Before planning the lesson, I reflected on the needs of my rural classroom. My learners respond more positively to practical, interactive activities than to long grammar explanations. Therefore, I planned a learner-centred revision lesson using pictures, real objects, pair work, group work, guided questions, visual materials, and sentence starters.",
      "I expected different ability levels in the classroom. Some learners usually complete activities quickly, while others need more time and individual guidance. Pair and group work were included so learners could support one another, build confidence, and participate actively.",
      "Assessment was planned as a continuous process through questioning, observation, and classroom discussion rather than only at the end of the lesson. My aim was to help learners remember the correct forms and use English confidently during classroom interaction.",
      "This planning connected with Vygotsky's view that learners develop understanding through interaction and with Communicative Language Teaching, where grammar is learned through meaningful use rather than memorisation.",
    ],
    postTeaching: [
      "Looking back on the lesson, I was pleased to see active learner participation from the beginning. The revision poster attracted attention, and pictures and real classroom objects helped learners understand near and far more clearly than in previous lessons.",
      "Pair work and group activities were successful. Learners enjoyed asking and answering questions with activity cards, and quieter learners became more involved after encouragement from classmates. This showed me again that collaboration creates a supportive space for risk-taking in English.",
      "A few learners still confused that and those. Instead of correcting them immediately, I used additional guiding questions and classroom objects so they could notice the difference themselves. Giving learners time to think was more useful than simply giving the correct answer.",
      "Time management needed improvement because some groups finished quickly while others needed support. I spent longer on guided practice than planned, but this was worthwhile because meaningful understanding was more important than mechanically completing every activity.",
      "Overall, the lesson achieved its intended outcomes and strengthened my confidence in learner-centred grammar teaching. In future, I plan to include more real-life communicative activities, extension tasks for faster learners, and continued support for learners who need guidance.",
    ],
    references: [
      "Black, P., & Wiliam, D. (1998). Assessment and classroom learning. Assessment in Education: Principles, Policy & Practice, 5(1), 7–74.",
      "Educational Publications Department. (2019). English: Grade 6 pupil's book. Ministry of Education, Sri Lanka.",
      "Richards, J. C., & Rodgers, T. S. (2014). Approaches and methods in language teaching (3rd ed.). Cambridge University Press.",
      "Schön, D. A. (1983). The reflective practitioner: How professionals think in action. Basic Books.",
      "Vygotsky, L. S. (1978). Mind in society: The development of higher psychological processes. Harvard University Press.",
    ],
  },
  {
    number: "02",
    title: "Listening for Specific Information - School Environment Day",
    skill: "Listening",
    model: "Pre-listening, while-listening, and post-listening",
    pdfHref: "/docs/depth-reflection/lesson-2-listening-skills.pdf",
    preTeaching: [
      "Listening is challenging for many Grade 6 learners because they have limited opportunities to hear spoken English outside the classroom. Some learners try to remember every word instead of listening for key information, which causes confusion.",
      "I selected the theme School Environment Day because it connects with learners' own school experiences such as cleaning the garden, planting trees, and collecting plastic. A familiar topic was expected to reduce anxiety and help learners listen for meaning.",
      "The task required learners to identify the event, date, time, place, activities, and materials to bring. To make this manageable, I planned the lesson in stages: vocabulary and prediction before listening, general understanding during the first listening, and specific information during the second listening.",
      "I prepared a word bank and allowed learners to compare answers with partners before class discussion. This was intended to reduce fear of mistakes and build confidence.",
      "The lesson reflected a learner-centred approach, social interaction, and formative assessment, where learning needs are identified during the lesson rather than only at the end.",
    ],
    postTeaching: [
      "The Environment Day theme immediately captured learners' attention. During the opening discussion, many learners shared experiences of cleaning the school compound and planting trees, confirming that familiar contexts increase motivation.",
      "The prediction activity was successful because learners began listening with a purpose. Most learners identified the main event after the first listening without much difficulty.",
      "During the second listening, most learners completed the information grid successfully. A few learners struggled to write quickly, confused starting and finishing times, or tried to write full sentences rather than short notes.",
      "Pair checking created a supportive learning environment. Learners discussed answers respectfully, and several unsure learners became more confident after talking with partners.",
      "This lesson reminded me that listening is not only about hearing words. It is about helping learners develop confidence, concentration, prediction, key-word listening, and independence.",
    ],
    references: [
      "Black, P., & Wiliam, D. (1998). Assessment and classroom learning. Assessment in Education: Principles, Policy & Practice, 5(1), 7–74.",
      "Educational Publications Department. (2019). English: Grade 6 Pupil's Book. Ministry of Education, Sri Lanka.",
      "Field, J. (2008). Listening in the Language Classroom. Cambridge University Press.",
      "Richards, J. C., & Rodgers, T. S. (2014). Approaches and Methods in Language Teaching (3rd ed.). Cambridge University Press.",
      "Vygotsky, L. S. (1978). Mind in Society: The Development of Higher Psychological Processes. Harvard University Press.",
    ],
  },
  {
    number: "03",
    title: "Using English in Different Everyday Contexts",
    skill: "Speaking",
    model: "3P Model with role play and peer assessment",
    pdfHref: "/docs/depth-reflection/lesson-3-speaking.pdf",
    preTeaching: [
      "This lesson was planned to help Grade 6 learners use suitable English expressions in familiar everyday situations such as the classroom, a shop, a bus stop, and the school office. I wanted learners to move beyond memorising sentences and choose language according to context.",
      "I expected classroom and shop situations to be easier, while bus stop and school office contexts might require more support with polite requests. Picture cards, model dialogues, and an expression bank were prepared for this reason.",
      "Role play was selected because speaking develops through actual use. Mixed-ability pairs were planned so stronger learners could support others while both partners still had speaking roles.",
      "I anticipated that some learners might depend too much on written dialogue frames. Therefore, I planned to use cue words during final role play, helping learners move gradually from support to more natural speaking.",
      "A peer-assessment checklist was included to focus on suitable language, politeness, pronunciation, and turn-taking, making assessment part of learning rather than a final teacher judgement.",
    ],
    postTeaching: [
      "The lesson was lively from the beginning. Picture cards helped learners identify contexts quickly, and many suggested suitable expressions for classroom and shop situations.",
      "Model dialogues gave learners a clear starting point. Most understood polite words such as please, thank you, may I, and could I. Some learners confused expressions for bus stop and school office situations, so I guided them with questions about who they were speaking to and how polite they needed to be.",
      "Pair role plays were the strongest part of the lesson. Learners enjoyed changing roles, and quieter learners participated more confidently after rehearsal with a partner.",
      "Some pairs read from full dialogues instead of speaking naturally. This showed that dialogue frames helped, but also created dependence. Next time, I would move from full frames to key words more gradually.",
      "The lesson showed that communicative teaching requires careful support, clear contexts, balanced participation, and gradual removal of scaffolding. Rural learners can communicate confidently when given familiar situations and a safe environment.",
    ],
    references: [
      "Black, P., & Wiliam, D. (1998). Assessment and classroom learning. Assessment in Education: Principles, Policy & Practice, 5(1), 7–74.",
      "Harmer, J. (2015). The practice of English language teaching (5th ed.). Pearson.",
      "Richards, J. C., & Rodgers, T. S. (2014). Approaches and methods in language teaching (3rd ed.). Cambridge University Press.",
      "Vygotsky, L. S. (1978). Mind in society: The development of higher psychological processes. Harvard University Press.",
    ],
  },
  {
    number: "04",
    title: "Reading a Simple Folk Story - Andare and the Sweet Mangoes",
    skill: "Reading",
    model: "Pre-reading, while-reading, and post-reading",
    pdfHref: "/docs/depth-reflection/lesson-4-reading-skills.pdf",
    preTeaching: [
      "I selected this lesson because reading is more than pronouncing words correctly. It involves understanding ideas, identifying important information, thinking critically, and expressing personal opinions.",
      "Many Grade 6 learners read only to answer direct comprehension questions. I wanted this lesson to develop higher-order reading skills through prediction, sequencing, inference, evidence-based responses, and personal reflection.",
      "Andare and the Sweet Mangoes was chosen because Andare is familiar in Sri Lankan culture. I planned to use pictures to activate background knowledge and encourage learners to predict characters, setting, and problem before reading.",
      "Because reading ability varies widely, I prepared scaffolds such as teacher modelling, story maps, labelled icons, event strips, paragraph cues, and sentence frames. These supports were intended to help all learners participate without lowering expectations.",
      "Assessment was embedded throughout prediction, guided reading, sequencing, character analysis, retelling, and exit slips so I could observe understanding and give immediate feedback.",
    ],
    postTeaching: [
      "Learners were enthusiastic from the beginning. The picture of Andare captured attention, and many learners shared stories they had heard before. This confirmed that cultural connections increase motivation.",
      "The story map helped learners identify characters, setting, and the main problem. Learners who usually struggle with reading participated more confidently when using visual organisers and prompts.",
      "The sequencing activity generated active discussion. Several learners began returning to the text for evidence rather than depending only on memory.",
      "The character-and-message activity showed both strengths and challenges. Many learners identified Andare as clever, but some needed prompting to support opinions with evidence from the text.",
      "This lesson strengthened my understanding that reading is an active thinking process. In future, I will include more evidence-based discussion, differentiated questioning, and authentic texts.",
    ],
    references: [
      "Black, P., & Wiliam, D. (1998). Assessment and classroom learning. Assessment in Education: Principles, Policy & Practice, 5(1), 7–74.",
      "Educational Publications Department. (2019). English: Grade 6 Pupil's Book. Ministry of Education, Sri Lanka.",
      "Harmer, J. (2015). The Practice of English Language Teaching (5th ed.). Pearson.",
      "Richards, J. C., & Rodgers, T. S. (2014). Approaches and Methods in Language Teaching (3rd ed.). Cambridge University Press.",
      "Vygotsky, L. S. (1978). Mind in Society: The Development of Higher Psychological Processes. Harvard University Press.",
    ],
  },
  {
    number: "05",
    title: "Teaching Adverbs through Guided Discovery",
    skill: "Grammar",
    model: "Guided Discovery Model",
    pdfHref: "/docs/depth-reflection/lesson-5-adverbs.pdf",
    preTeaching: [
      "Before planning this lesson, I reflected on learners' previous grammar lessons and realised that many remembered rules without understanding how grammar helps communication. They could identify action verbs but struggled to describe how an action happened.",
      "I deliberately planned this lesson using Guided Discovery rather than beginning with a grammar explanation. Learners would observe actions, compare examples, discuss ideas, and gradually discover that adverbs describe how an action happens.",
      "Because of mixed ability levels, I planned teacher demonstrations, action picture cards, Think-Pair-Share, group discussion, picture clues, sentence starters, and an adverb word bank.",
      "I expected some learners to confuse adjectives and adverbs. Guided questions such as Which word tells us how the action happened? were prepared to help learners think critically about language.",
      "Assessment was integrated throughout through observation, questioning, peer discussion, individual practice, and peer assessment.",
    ],
    postTeaching: [
      "Teacher demonstrations immediately captured learners' attention. By acting out contrasting actions such as running quickly and walking slowly, learners experienced the language before learning the formal grammar term.",
      "The Guided Discovery stage was successful. Learners compared sentence pairs and identified the additional information provided by adverbs. Further questioning helped them distinguish between describing a person and describing an action.",
      "Group work created an active learning environment, with learners discussing pictures and justifying their choice of adverbs. However, stronger learners sometimes dominated, so future lessons should assign clearer group roles.",
      "Most learners identified suitable adverbs and formed simple sentences, but some still confused adjectives and adverbs. Guiding questions helped them reconsider the purpose of the describing word.",
      "This lesson strengthened my belief that effective grammar teaching depends on the quality of learning experiences teachers create, not only on what teachers explain.",
    ],
    references: [
      "Black, P., & Wiliam, D. (1998). Assessment and classroom learning. Assessment in Education: Principles, Policy & Practice, 5(1), 7–74.",
      "Bruner, J. S. (1966). Toward a Theory of Instruction. Harvard University Press.",
      "Educational Publications Department. (2019). English: Grade 6 Pupil's Book. Ministry of Education, Sri Lanka.",
      "Harmer, J. (2015). The Practice of English Language Teaching (5th ed.). Pearson.",
      "Richards, J. C., & Rodgers, T. S. (2014). Approaches and Methods in Language Teaching (3rd ed.). Cambridge University Press.",
      "Vygotsky, L. S. (1978). Mind in Society: The Development of Higher Psychological Processes. Harvard University Press.",
    ],
  },
];
